### ISSUE TITLE
Можно ли взять этот код в репо i2pd?

### ISSUE THREAD

**Issue by l-n-s** [gxcreator/i2pd-openwrt#5]
Народ жаждет OpenWRT, имеет смысл брать этот код в репо i2pd? Например, положить в директорию `i2pd/contrib/openwrt`

**Comment by Shulyaka** [comment]
Лучше сразу послать в апстрим в openwrt/packages. Могу предложить заняться этим чуть попозже, когда время свободное появится.

**Comment by orignal** [comment]
@Shulyaka это было бы прекрасно

**Comment by gxcreator** [comment]
Да, конечно
